credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin User
      password: "$2b$12$2CBXWU2Srh5cZCc4IgZNPetJvX.Vvp8rYhCsEEzI9N5vgd/6BLOa." # Generated hash
cookie:
  expiry_days: 30
  key: e829e0cdcedd15a6e1205c12b6e92d69fc07de7e362dbd7cb5e6dd8a4ac339a0 # Generated key
  name: admin_cookie
preauthorized:
  emails: [] 