apiVersion: 1

contactPoints:
  - orgId: 1
    name: telegram-alerts
    receivers:
      - uid: telegram-alert-receiver
        type: telegram
        settings:
          bottoken: ${TELEGRAM_ALERT_BOT_TOKEN}
          chatid: ${TELEGRAM_ALERT_CHAT_ID}
          parse_mode: HTML
          disable_web_page_preview: true
        disableResolveMessage: false
